In [2]:
import numpy as np

In [3]:
data = np.genfromtxt('salaries.txt', delimiter=',', dtype=str)
print(type(data))

<class 'numpy.ndarray'>


In [45]:
# 查看数据量和内容
print(data.shape)
print(data.shape[0])
print(data.shape[1])

(398, 7)
398
7


In [46]:
# 查看具体数据
print(data[:5])

[['""' '"rank"' '"discipline"' '"yrs.since.phd"' '"yrs.service"' '"sex"'
  '"salary"']
 ['"1"' '"Prof"' '"B"' '19' '18' '"Male"' '139750']
 ['"2"' '"Prof"' '"B"' '20' '16' '"Male"' '173200']
 ['"3"' '"AsstProf"' '"B"' '4' '3' '"Male"' '79750']
 ['"4"' '"Prof"' '"B"' '45' '39' '"Male"' '115000']]


In [4]:
# 去掉表头
header = data[0]
data = data[1:]
print(data.shape)
print(data[:5])

(397, 7)
[['"1"' '"Prof"' '"B"' '19' '18' '"Male"' '139750']
 ['"2"' '"Prof"' '"B"' '20' '16' '"Male"' '173200']
 ['"3"' '"AsstProf"' '"B"' '4' '3' '"Male"' '79750']
 ['"4"' '"Prof"' '"B"' '45' '39' '"Male"' '115000']
 ['"5"' '"Prof"' '"B"' '40' '41' '"Male"' '141500']]


In [5]:
# 将这个ndarray全部数字化，每一行要知道取值范围
rank = data[:, 1]
discipline = data[:, 2]
yrs_since_phd = data[:, 3]
yrs_service = data[:, 4]
sex = data[:, 5]
salary = data[:, 6]

print(set(rank))
print(set(discipline))
print(set(sex))
print(yrs_since_phd[:5])
print(yrs_service[:5])
print(sex[:5])
print(salary[:5])


{'"Prof"', '"AsstProf"', '"AssocProf"'}
{'"A"', '"B"'}
{'"Female"', '"Male"'}
['19' '20' '4' '45' '40']
['18' '16' '3' '39' '41']
['"Male"' '"Male"' '"Male"' '"Male"' '"Male"']
['139750' '173200' '79750' '115000' '141500']


In [6]:
yrs_since_phd = yrs_since_phd.astype('int')
yrs_service = yrs_service.astype('int')
salary = salary.astype('int')
print(yrs_since_phd[:5])
print(yrs_service[:5])
print(salary[:5])

[19 20  4 45 40]
[18 16  3 39 41]
[139750 173200  79750 115000 141500]


In [7]:
# 定义一些映射关系
rank2num = {
    '"AssocProf"':0,
    '"AsstProf"':1,
    '"Prof"':2
}
discipline2num = {
    '"A"':0,
    '"B"':1
}
sex2num = {
    '"Male"':0,
    '"Female"':1
}
# 修改不起作用
for value in rank:
    value = rank2num[value]
print(rank[:5])
# 要访问原对象修改

# rank[0] = 2
# print(rank[:5])
# rank[0] = '"Prof"'

['"Prof"' '"Prof"' '"AsstProf"' '"Prof"' '"Prof"']


In [8]:
for index, value in enumerate(rank):
    rank[index] = rank2num[value]
for index, value in enumerate(discipline):
    discipline[index] = discipline2num[value]
for index, value in enumerate(sex):
    sex[index] = sex2num[value]

print(rank[:5])
print(discipline[:5])
print(sex[:5])

['2' '2' '1' '2' '2']
['1' '1' '1' '1' '1']
['0' '0' '0' '0' '0']


In [9]:
rank = rank.astype(int)
discipline = discipline.astype(int)
sex = sex.astype(int)
print(rank[:5])
print(discipline[:5])
print(sex[:5])

[2 2 1 2 2]
[1 1 1 1 1]
[0 0 0 0 0]


In [54]:

print(rank[:5])
print(discipline[:5])
print(yrs_since_phd[:5])
print(yrs_service[:5])
print(sex[:5])
print(salary[:5])


[2 2 1 2 2]
[1 1 1 1 1]
[19 20  4 45 40]
[18 16  3 39 41]
[0 0 0 0 0]
[139750 173200  79750 115000 141500]


In [11]:
data = np.vstack((rank, discipline, yrs_since_phd, yrs_service, sex, salary))
print(data.shape)
data = data.T

(6, 397)


In [12]:

print(data.shape)
print(data[:5])

(397, 6)
[[     2      1     19     18      0 139750]
 [     2      1     20     16      0 173200]
 [     1      1      4      3      0  79750]
 [     2      1     45     39      0 115000]
 [     2      1     40     41      0 141500]]


In [29]:
# 求出3年内入职的老师的数量
print(np.sum(data[:, 3] <= 3))
# 求出薪水找过18w的老师的数量
print(np.sum(data[:, 5] >= 180000))
# 求出老师们的平均薪资
print(np.mean(data[:, 5]))
print('{:.2f}'.format(np.mean(data[:, 5])))

# 统计男女性别比例？统计不同教职的数量？工作时间超过10年单身薪资低于10w的人数？
# print(data[np.where((data[:, 5] <= 100000) & (data[:, 3] >= 10))][:, [3,5]]) # 获取某些特定行和列的方法
index = np.where((data[:, 5] <= 100000) & (data[:, 3] >= 10)) # 多条件查询的方法：np.where
print(np.count_nonzero(index)) # 统计非0个数的方法

61
12
113706.45843828715
113706.46
48
48
